apiVersion: apps/v1
kind: Job
metadata:
  name: basket
  namespace: domaci1
spec:
  replicas: 1
  selector:
    matchLabels:
      zadatak: jedan
  template:
    metadata:
      labels:
        zadatak: 
    spec:
      containers:
      - name: domaci1
        image: dusicaraf:1.0
